# Generated by Django 3.1.7 on 2021-08-14 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
