# Generated by Django 3.1.7 on 2021-08-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210815_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='type',
            new_name='ctype',
        ),
    ]
