# Generated by Django 3.1.7 on 2021-08-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210815_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='ctype',
            field=models.CharField(choices=[('1', 'For Motion'), ('2', 'Against Motion')], max_length=50, null=True, verbose_name='Claim Type'),
        ),
    ]
