# Generated by Django 3.1.7 on 2021-08-14 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210814_1710'),
        ('app', '0006_auto_20210815_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userroles'),
        ),
    ]
