# Generated by Django 3.1.7 on 2021-08-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210815_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='managers',
        ),
    ]
