# Generated by Django 3.1.7 on 2021-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_discussion_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='p1dislike',
            field=models.IntegerField(blank=True, null=True, verbose_name='P1 likes'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='p1like',
            field=models.IntegerField(blank=True, null=True, verbose_name='P1 likes'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='p2dislike',
            field=models.IntegerField(blank=True, null=True, verbose_name='P2 likes'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='p2like',
            field=models.IntegerField(blank=True, null=True, verbose_name='P2 likes'),
        ),
    ]
