# Generated by Django 3.1.7 on 2021-08-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210815_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
