# Generated by Django 3.1.7 on 2021-08-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210816_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='for_claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discussion'),
        ),
    ]
