# Generated by Django 3.1.7 on 2021-08-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210814_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(null=True, verbose_name='Points'),
        ),
    ]
